### ISSUE TITLE
Border inverted Internet Explorer 

### ISSUE THREAD

**Issue by mcrnic** [Chaptykov/mindmap#1]
When using direction:rtl
Internet explorer inverts left and right border.
Adding 
direction: ltr; 
to 
.children_leftbranch .children__item:first-child:before 
.children_leftbranch .children__item:last-child:before

will fix the issue.

**Comment by Chaptykov** [comment]
Thanks for the issue. It's fixed in 4aef646.

**Comment by lucianobonfim** [comment]
Chaptykov,

I need to create buttons (+ and -) to expand or not the nodes and their children in your mindmap.
Equal a tree (the same function DEL in your JS, but visible and invisible)

may you help-me? 

what is your price to do this service for me?

email: luciano@bonfimsistemas.com.br
email: lazevedo.email@gmail.com

thanks

**Comment by Chaptykov** [comment]
I made new issue about this improvement. I'll do it this week.
